container:
  image: rust:latest

sample_task:
  matrix:
    - container:
        image: rust:latest
    - container:
        image: rustlang/rust:nightly
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  build_script: cargo build
  test_script: cargo test
  lint_script:
    - cargo clippy --all-targets --all-features -- -D warnings
  before_cache_script: rm -rf $CARGO_HOME/registry/index
