container:
  image: rust:latest

sample_task:
  matrix:
    - container:
        image: rust:latest
    - container:
        image: rustlang/rust:nightly
  cargo_cache:
    folder: $CARGO_HOME/registry
  build_script: cargo build --verbose
  test_script: cargo test --verbose
  clippy_script:
    - rustup update
    - rustup component add clippy
    - cargo clippy --all-targets --all-features -- -D warnings
  before_cache_script: rm -rf $CARGO_HOME/registry/index
